### ISSUE TITLE
Infinite resolution in Gradle for snapshot dependency

### ISSUE THREAD

**Issue by ben-manes** [jitpack/jitpack.io#1251] opened 2017-03-29 09:11 UTC
The [icafe](https://github.com/dragon66/icafe) project uses the jitpack convention but only releases snapshot versions to Sonatype's repository. When compiling Gradle is able to resolve the jar.

Unfortunately when using [dependencyUpdates](https://github.com/ben-manes/gradle-versions-plugin) to query for potential upgrades, the metadata query gets stuck. The build loops forever and outputs to the debug log statements like,
```
02:05:38.498 [DEBUG] [org.apache.http.impl.execchain.MainClientExec]
Executing request GET /com/github/dragon66/icafe/index.html?building=8 HTTP/1.1
```
where the `building=N` gradually increases but no timeout occurs. The short-term workaround is to remove `jitpack` prior to running the task, but its a surprising side effect.

**Comment by jitpack-io** [comment] 2017-03-29 12:36
Having a look.
Interesting that it tries to get `index.html`. Shouldn't it be looking for `maven-metadata.xml`?

**Comment by ben-manes** [comment] 2017-03-29 13:55
I think it queries the directory and receives a redirect. The directory query would let it distinguish between ivy, maven, etc.

**Comment by Mathbl** [comment] 2017-04-02 16:56
I'm also encountering that issue. I'm not sure what changed on my side, but since a couple of days, dependencyUpdates gets stuck everytime. At first, I thought there was a problem with one of my dependency that uses jitpack, but they build correctly when I check on the jitpack website. 

I tried removing the dependency that was causing the infinite resolution, but then, the next one doesn't resolve either.

**Comment by ben-manes** [comment] 2017-04-02 17:08
@Mathbl You can remove jitpack from `dependencyUpdates` without effecting your build, e,g.
```gradle
repositories {
  maven { name 'jitpack'; url 'https://jitpack.io' }
}
tasks.dependencyUpdates.doFirst {
  repositories.removeAll { it.name == 'jitpack' }
}
```

The plugin is using Gradle to handle the resolution (effectively `+` with a pretty report). So problems tend to be either Gradle or repository bugs, since the plugin is just the glue logic.

**Comment by Mathbl** [comment] 2017-04-03 15:05
@ben-manes Indeed! Thanks for the trick, that'll do it for now. Still not sure about the cause of the sudden issue with resolving from jitpack, but I'll subscribe to this issue and see how it goes. Thanks again.

**Closed** 2018-12-04 08:46 UTC
