### ISSUE TITLE
401 Unauthorized for public repo when building with private repo.

### ISSUE THREAD

**Issue by disparate** [jitpack/jitpack.io#3759] opened 2019-03-01 11:47 UTC
I receive 401 Unauthorized response for public repo if there's also a private repo inside app dependencies.

Here's stacktrace returned from gradle:

```
Warning: project ':app': Unable to build Kotlin project configuration
Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':app:debugImplementationDependenciesMetadata'.
Caused by: org.gradle.internal.resolve.ArtifactResolveException: Could not determine artifacts for com.github.phrase:android-sdk:1.0.1
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/phrase/android-sdk/1.0.1/android-sdk-1.0.1.aar'.
Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not HEAD 'https://jitpack.io/com/github/phrase/android-sdk/1.0.1/android-sdk-1.0.1.aar'. Received status code 401 from server: Unauthorized
```
My app's build.gradle 
```
dependencies {
   ...
    implementation 'com.github.app-craft.android-utils:subs:1.1.7' //private
    implementation 'com.github.phrase:android-sdk:1.0.1' //public
}
```
And here's root's build.gradle
```

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://jitpack.io"
            credentials { username <auth_token> }
        }
    }
}
```

It works ok if I remove dependency to a private repo, but almost always it returns 401 to a public repo  if I try to use both.

**Comment by jitpack-io** [comment] 2019-03-01 13:36
Hi,

GitHub is reporting '404 Not Found' for this repository: 
https://github.com/phrase/android-sdk

Perhaps it was public previously but at the moment it looks like it is private.

**Comment by disparate** [comment] 2019-03-03 20:44
Hello. Thanks for the response.
The repository is private indeed but I can always download that dependency if I don't use my own private dependency on jitpack. (That installation instructions for the lib https://help.phraseapp.com/phraseapp-over-the-air-ota/android-sdk-installation-instructions).
It also happens with other libs, not only that one.

**Comment by disparate** [comment] 2019-03-04 07:55
Also, I guess it's connected with that issue, I tried to open that url that returns 401 for me in browser:
https://jitpack.io/com/github/phrase/android-sdk/1.0.1/android-sdk-1.0.1.aar
It asks me to sign in.
But if I use "incognito" mode on browser it starts download the resource instantly.

**Comment by theSoenke** [comment] 2019-03-04 14:41
@jitpack-io The android-sdk repository is private on Github but the artifacts are public on Jitpack. Is it possible that Jitpack validates the credentials for the public android-sdk repository which causes the failure?

**Comment by jitpack-io** [comment] 2019-03-04 15:49
@theSoenke Thanks for the clarification! You're right, the artifacts are public so JitPack shouldn't be asking for credentials.
@disparate Does it work if you only use the 'private' dependency?

**Comment by disparate** [comment] 2019-03-04 15:50
@jitpack-io 
Yes it is. 
The problem only happens when I use both private and public.

**Comment by jitpack-io** [comment] 2019-03-05 07:01
Got it. With your help we can now reproduce this issue. Working on a fix...

**Comment by jitpack-io** [comment] 2019-03-11 09:56
Hi @disparate ,

Should be fixed now.

**Comment by disparate** [comment] 2019-03-11 11:32
@jitpack-io 
Seems to be ok now, thanks.

**Closed** 2019-03-12 07:01 UTC
Labels: bug

**Comment by Stkrr002** [comment] 2024-07-16 10:15
Could not GET 'https://jitpack.io/com/github/florent37/inline-activity-result-kotlin/1.0.4/inline-activity-result-kotlin-1.0.4.pom'. Received status code 401 from server: Unauthorized

facing smililar with this github public repo while fetching it in private repo using gitlab runner.

@jitpack-io

**Comment by Muitsu** [comment] 2024-08-31 01:58
Any workarounds? I've been stuck for a week and still haven't found a solution.

 Could not GET [](https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom.) Received status code 401 from server: Unauthorized

Caused by: org.gradle.api.resources.ResourceException: Could not get resource '[](https://jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom)'.

Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET '[](https://jitpack.io/com/github/warkiz/widget/indicatorseekbar/2.1.2/indicatorseekbar-2.1.2.pom)'. Received status code 401 from server: Unauthorized

Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.github.warkiz.widget:indicatorseekbar:2.1.2.

Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://jitpack.io/com/github/warkiz/widget/indicatorseekbar/2.1.2/indicatorseekbar-2.1.2.pom'.
