### ISSUE TITLE
Android Studio fails to resolve projects

### ISSUE THREAD

**Issue by XorgMC** [jitpack/jitpack.io#424] opened 2016-02-08 20:55 UTC
hi,
I'm trying to use a project from jitpack, specifically material-dialogs. I added jitpack.io as a maven repo in my root build.gradle file and added a compile-dependency, but android studio fails with "Failed to resolve: com.github.afollestad.materials-dialogs:core:0.8.5.4". I need this for another project, but I now tried with a blank android project to test this. I just added the two lines (maven repo url and compile dependency).

[Project Root]/build.gradle:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

[Project Root]/app/build.gradle:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.example.xorg.foobar"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.github.afollestad.material-dialogs:core:0.8.5.4'
}
```

I am using Android Studio 1.5.1 on Arch Linux x86_64 and openjdk 7

Any clue?

**Comment by grote** [comment] 2016-02-08 22:54
This sounds like a duplicate of #423. Could you maybe try to run `gradle build --info` on the command line to see whether it is in fact the same problem?

**Comment by jitpack-io** [comment] 2016-02-09 09:07
Hi @XorgMC 

Your gradle file is correct so it should work. @grote is right that we need to see a more detailed error message. If run `./gradlew assembleDebug --info` does it tell you the cause of the error?

**Comment by XorgMC** [comment] 2016-02-09 12:39
@jitpack-io 

got the following result:
```
Resource missing. [HTTP GET: https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.4/core-0.8.5.4.pom]
Resource missing. [HTTP HEAD: https://jcenter.bintray.com/com/github/afollestad/material-dialogs/core/0.8.5.4/core-0.8.5.4.jar]

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.4.
     Required by:
         Foobar:app:unspecified
      > Could not resolve com.github.afollestad.material-dialogs:core:0.8.5.4.
         > Could not get resource 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.4/core-0.8.5.4.pom'.
            > Could not GET 'https://jitpack.io/com/github/afollestad/material-dialogs/core/0.8.5.4/core-0.8.5.4.pom'.
               > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 6.664 secs
```

Xorg

**Comment by grote** [comment] 2016-02-09 12:41
So it is exactly the same error as mine and thus a duplicate of #423.

**Comment by jitpack-io** [comment] 2016-02-09 12:43
Thank you @XorgMC! Yes, @grote same error. Couldn't reproduce the error yet 
In the mean time, can anyone try Gradle 2.11? There's a fix in there for SSL certificates that could be related

**Comment by jitpack-io** [comment] 2016-02-09 13:33
Ok, this is a weird one.
Couldn't reproduce the error locally so figured it could be CDN related. Saw that you both are from Germany so fired up a VPS in Frankfurt. Bingo! Got the same problem.

Using Gradle 2.11 solves the issue. Will file a ticket with the CDN provider

**Comment by grote** [comment] 2016-02-09 13:38
Just for the record, I was not connecting from Germany when getting this error.

**Comment by jitpack-io** [comment] 2016-02-09 16:29
Another way to solve it is by upgrading to Java 8. This error seems to only occur wiht openjdk7.

**Closed** 2016-02-15 09:33 UTC

**Comment by PSNAppz** [comment] 2018-10-17 05:57
This worked for me
`        jcenter { url "http://jcenter.bintray.com/" }
`
