### ISSUE TITLE
Can't find android.support in jitpack.io

### ISSUE THREAD

**Issue by simpleton** [jitpack/jitpack.io#27] opened 2015-03-12 08:04 UTC
I think support package should store in sdk folder, but the gradle try to find it in jitpack. I've no idea to walk around this issue.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not resolve com.android.support:appcompat-v7:22+.
     Required by:
         letsgo-android:app:unspecified
      > Failed to list versions for com.android.support:appcompat-v7.
         > Unable to load Maven meta-data from https://jitpack.io/com/android/support/appcompat-v7/maven-metadata.xml.
            > Could not GET 'https://jitpack.io/com/android/support/appcompat-v7/maven-metadata.xml'. Received status code 400 from server: Expecting: /com/github/user/repo[/module]/version/repo-version.pom
```

**Comment by jitpack-io** [comment] 2015-03-12 10:21
Hi @simpleton,

com.android.support:appcompat-v7 is not hosted on jitpack. Afaik, its also not hosted on any public repository.

You could try https://github.com/mosabua/maven-android-sdk-deployer and then add mavenLocal() to your repositories list before jitpack.  

Is your project on GitHub?

**Comment by jitpack-io** [comment] 2015-03-15 11:50
Without seeing your build files it's hard to tell where the problem is. Closing the issue for now but please reopen if there's still a problem. Also feel free to get in touch on gitter https://gitter.im/jitpack-io

**Closed by jitpack-io** 2015-03-15 11:50 UTC
