### ISSUE TITLE
MarkdownView/0.6.0 build

### ISSUE THREAD

**Issue by tiagohm** [jitpack/jitpack.io#1167] opened 2017-03-04 16:07 UTC
Log https://jitpack.io/com/github/tiagohm/MarkdownView/0.6.0/build.log

**Comment by jitpack-io** [comment] 2017-03-04 16:08
Hi @tiagohm 

It looks like this is the cause of the error:
`WARNING: gradle/wrapper/gradle-wrapper.jar does not exist! Needs to be committed.
ERROR: Gradle wrapper not found. Please add. Using default gradle to build.`

Sometimes gradle-wrapper.jar get ignored with .gitignore file.

**Comment by tiagohm** [comment] 2017-03-04 16:11
See this log Builded successfully https://jitpack.io/com/github/tiagohm/MarkdownView/0.5.0/build.log

**Comment by tiagohm** [comment] 2017-03-04 16:18
I do not modify the .gitignore. I just updated to `classpath 'com.android.tools.build: gradle: 2.3.0'`  and gradle 3.3.

**Comment by jitpack-io** [comment] 2017-03-04 16:23
Ah ok, the previous build succeeded because it was using the default gradle 3.1. When you upgraded it stopped working. 

There is an easy fix. Simply commit the gradle-wrapper.jar under here:
https://github.com/tiagohm/MarkdownView/tree/master/gradle/wrapper

It gets ignored by default with current .gitignore:
https://github.com/tiagohm/MarkdownView/blob/master/.gitignore#L43

**Comment by jitpack-io** [comment] 2017-03-06 08:19
Looks like newer builds were ok

**Closed** 2017-03-08 21:20 UTC
